version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: recipe123
      POSTGRES_DB: recipe_app
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: recipe123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: recipe_app
      JWT_SECRET: your_secret_key
      SPOONACULAR_API_KEY: f973aa70f8104d0babff704c934084db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: